### ISSUE TITLE
A bug in exporting tex may be fixed

### ISSUE THREAD

**Issue by BDFFZI** [luvoid/Blender-CM3D2-Converter#15]
I encounter the following error when exporting tex
> Python: Traceback (most recent call last):
  File "C:\Users\MyComputer\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\CM3D2 Converter\tex_export.py", line 49, in invoke
    self.path = img.get('cm3d2_path')
  File "D:\blender\3.3\scripts\modules\bpy_types.py", line 823, in __setattr__
    return setattr(properties, attr, value)
TypeError: bpy_struct: item.attr = val: IMAGE_OT_export_cm3d2_tex.path doesn't support None from string types

I tried to fix it, and it was really simple, like this.

Will this part of the code At CM3D2 Converter\tex_export.py , line 49
```
        self.path = img.get('cm3d2_path')
        if self.path is None:
            self.path = common.get_tex_cm3d2path(self.filepath)
            img['cm3d2_path'] = self.path
```
Replace with the following
```
        path = img.get('cm3d2_path')
        if path is None:
            path = common.get_tex_cm3d2path(self.filepath)
            img['cm3d2_path'] = path
        self.path = path
```
 So can we fix this in a later version?

**Comment by luvoid** [comment]
That is... really simple. Yeah. I'll add it to the testing branch... three years later, but should be easy.
